# site settings
title: rundowntown
subtitle: 123
email: daniel.forcade@uvm.edu
description: rundowntown | website
baseurl: "/ForcadeBio381"
url: # the base hostname & protocol for your site
author: daniel forcade
street_address:
city:
state: VT
zip_code:
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: github.com/rundowntown
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
